services:
  - type: static
    name: ebirth-frontend
    rootDir: .
    buildCommand: npm ci && npm run build
    staticPublishPath: build
    pullRequestPreviewsEnabled: false
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://ebirth-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
